services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - 6333:6333 # tcp
      - 6334:6334 # grpc
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always

volumes:
  qdrant_data:
